services:
  db:
    image: mysql:9.1.0
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: rest_udemy
    ports:
      - "3308:3306"
    expose:
      - 3306
    networks:
      - api
  restApi:
    image: 1vancn/restapi:latest
    restart: always
    build: .
    working_dir: /restApi
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://db:3306/rest_udemy?useTimezone=true&serverTimezone=UTC
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: 123
    #command: mvn spring-boot:run
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - api

  portainer:
    image: portainer/portainer-ce:latest
    restart: always
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - partainer_data:/data
    networks:
      - api

volumes:
  partainer_data:

networks:
  api:
    driver: bridge