cors:
  originPatterns: http://localhost:8080,http://localhost:3000
spring:
  application:
    name: apiRest
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_udemy?useTimezone=true&serverTimezone=UTC
    password: 123
    username: root
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
    show-sql: false
    open-in-view: false
logging:
  level:
    com.brainyit.rest.apirest.service.impl: DEBUG